In [1]:
from pathlib import Path
import pandas as pd

from sqlalchemy import create_engine

In [2]:
BASE_DIR = Path.cwd().parent

PROCESSED_DIR = (
    BASE_DIR
    / "data"
    / "processed"
)

DB_PATH = (
    BASE_DIR
    / "data"
    / "db"
    / "bluestock_mf.db"
)

print(PROCESSED_DIR)
print(DB_PATH)

c:\Users\lambd\Desktop\BlueStock_project\bluestock_mf_capstone\data\processed
c:\Users\lambd\Desktop\BlueStock_project\bluestock_mf_capstone\data\db\bluestock_mf.db

In [3]:
funds = pd.read_csv(
    PROCESSED_DIR /
    "01_fund_master_clean.csv"
)

nav = pd.read_csv(
    PROCESSED_DIR /
    "02_nav_history_clean.csv"
)

performance = pd.read_csv(
    PROCESSED_DIR /
    "07_scheme_performance_clean.csv"
)

transactions = pd.read_csv(
    PROCESSED_DIR /
    "08_investor_transactions_clean.csv"
)

In [4]:
summary = pd.DataFrame({
    "Dataset": [
        "Fund Master",
        "NAV History",
        "Performance",
        "Transactions"
    ],
    "Rows": [
        len(funds),
        len(nav),
        len(performance),
        len(transactions)
    ],
    "Columns": [
        funds.shape[1],
        nav.shape[1],
        performance.shape[1],
        transactions.shape[1]
    ]
})

summary

        Dataset   Rows  Columns
0   Fund Master     40       15
1   NAV History  46000        3
2   Performance     40       19
3  Transactions  32778       13

In [5]:
print("FUNDS")
display(funds.isnull().sum())

print("NAV")
display(nav.isnull().sum())

print("PERFORMANCE")
display(performance.isnull().sum())

print("TRANSACTIONS")
display(transactions.isnull().sum())

FUNDS

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

NAV

amfi_code    0
date         0
nav          0
dtype: int64

PERFORMANCE

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

TRANSACTIONS

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [6]:
print(
    "Funds Duplicates:",
    funds.duplicated().sum()
)

print(
    "NAV Duplicates:",
    nav.duplicated().sum()
)

print(
    "Performance Duplicates:",
    performance.duplicated().sum()
)

print(
    "Transactions Duplicates:",
    transactions.duplicated().sum()
)

Funds Duplicates: 0
NAV Duplicates: 0
Performance Duplicates: 0
Transactions Duplicates: 0

In [7]:
funds.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [8]:
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [9]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [10]:
engine = create_engine(
    f"sqlite:///{DB_PATH}"
)

print("Connected Successfully")

Connected Successfully

In [11]:
tables = pd.read_sql(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    engine
)

tables

                name
0           dim_date
1           dim_fund
2           fact_nav
3   fact_performance
4  fact_transactions

In [12]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_funds
    FROM dim_fund
    """,
    engine
)

   total_funds
0           40

In [13]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_nav
    FROM fact_nav
    """,
    engine
)

   total_nav
0      46000

In [14]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_performance
    FROM fact_performance
    """,
    engine
)

   total_performance
0                 40

In [15]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_transactions
    FROM fact_transactions
    """,
    engine
)

   total_transactions
0               32778

In [16]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_funds
    FROM dim_fund
    """,
    engine
)

   total_funds
0           40

In [17]:
pd.read_sql(
    """
    SELECT
        category,
        COUNT(*) AS fund_count
    FROM dim_fund
    GROUP BY category
    """,
    engine
)

  category  fund_count
0     Debt           6
1   Equity          34

In [18]:
pd.read_sql(
    """
    SELECT *
    FROM fact_nav
    ORDER BY nav DESC
    LIMIT 10
    """,
    engine
)

   amfi_code    nav_date        nav
0     120844  2026-05-29  4268.5497
1     120844  2026-05-28  4266.9021
2     120844  2026-05-27  4264.9256
3     120844  2026-05-26  4262.3302
4     120844  2026-05-22  4260.3220
5     120844  2026-05-21  4259.2780
6     120844  2026-05-25  4259.2727
7     120844  2026-05-20  4258.9179
8     120844  2026-05-19  4256.2918
9     120844  2026-05-14  4255.9472

In [19]:
pd.read_sql(
    """
    SELECT
        AVG(return_3yr_pct)
        AS avg_return_3yr
    FROM fact_performance
    """,
    engine
)

   avg_return_3yr
0          14.089

In [20]:
pd.read_sql(
    """
    SELECT
        amfi_code,
        sharpe_ratio
    FROM fact_performance
    ORDER BY sharpe_ratio DESC
    LIMIT 10
    """,
    engine
)

   amfi_code  sharpe_ratio
0     120507          7.68
1     120844          6.18
2     101208          5.14
3     100025          1.84
4     119120          1.52
5     118636          1.33
6     100016          1.06
7     148567          1.06
8     120504          1.03
9     118632          1.00

In [21]:
pd.read_sql(
    """
    SELECT
        SUM(amount_inr)
        AS total_transaction_amount
    FROM fact_transactions
    """,
    engine
)

   total_transaction_amount
0              3.521580e+09

In [22]:
pd.read_sql(
    """
    SELECT
        state,
        COUNT(*) AS txn_count
    FROM fact_transactions
    GROUP BY state
    ORDER BY txn_count DESC
    LIMIT 10
    """,
    engine
)

            state  txn_count
0          Punjab       2965
1  Madhya Pradesh       2931
2      Tamil Nadu       2806
3         Gujarat       2780
4     West Bengal       2748
5         Haryana       2736
6       Telangana       2718
7   Uttar Pradesh       2695
8           Delhi       2677
9       Karnataka       2621

In [23]:
pd.read_sql(
    """
    SELECT
        amfi_code,
        return_5yr_pct
    FROM fact_performance
    ORDER BY return_5yr_pct DESC
    LIMIT 10
    """,
    engine
)

   amfi_code  return_5yr_pct
0     101207           23.80
1     119095           22.62
2     118634           21.88
3     119599           21.82
4     119598           20.67
5     149324           20.61
6     149323           19.00
7     119094           18.94
8     120842           17.75
9     100033           17.69

In [24]:
pd.read_sql(
    """
    SELECT
        AVG(nav)
        AS avg_nav
    FROM fact_nav
    """,
    engine
)

      avg_nav
0  269.570265

In [25]:
pd.read_sql(
    """
    SELECT
        state,
        SUM(amount_inr)
        AS total_amount
    FROM fact_transactions
    GROUP BY state
    ORDER BY total_amount DESC
    """,
    engine
)

             state  total_amount
0           Punjab   315780459.0
1       Tamil Nadu   315177237.0
2   Madhya Pradesh   308312493.0
3        Rajasthan   298645822.0
4          Gujarat   298358940.0
5      West Bengal   297182514.0
6        Telangana   290219284.0
7            Delhi   289633404.0
8    Uttar Pradesh   285368873.0
9          Haryana   279634354.0
10       Karnataka   273753570.0
11     Maharashtra   269513480.0

In [26]:
engine.dispose()

print("Database Connection Closed")

Database Connection Closed